export const words = [
  "apple", "angel", "arbor", "armor", "arrow", "beach", "beast", "bench", "blaze",
  "block", "brain", "brick", "bride", "brood", "cabin", "camel", "charm", "chess",
  "class", "cloud", "court", "craft", "crown", "dance", "daisy", "dream", "drink",
  "eagle", "earth", "elder", "entry", "faith", "feast", "flame", "flock", "flora",
  "focus", "frame", "fruit", "giant", "glory", "grain", "grass", "guard", "guest",
  "habit", "heart", "house", "image", "ivory", "jewel", "joker", "knack", "knoll",
  "laser", "light", "liver", "lover", "magic", "maple", "metal", "miner", "model",
  "money", "moral", "mount", "mouse", "music", "noble", "ocean", "onion", "pearl",
  "peace", "plant", "plate", "plaza", "pride", "prime", "prism", "puppy", "queen",
  "quest", "quiet", "quilt", "radar", "raven", "river", "robot", "ruler", "salad",
  "scene", "scale", "sheep", "shore", "sight", "smile", "solar", "space", "spice",
  "spoon", "stack", "stone", "storm", "sugar", "table", "tiger", "token", "track",
  "trail", "trick", "unity", "vapor", "valor", "vivid", "voice", "water", "wheat",
  "wheel", "white", "whole", "world", "youth", "zebra", "abyss", "bison", "cliff",
  "coral", "ethos", "globe", "olive", "pixie", "realm", "ridge", "scout", "spike",
  "swarm", "torch", "whale", "acorn", "amber", "arena", "badge", "balmy", "birch",
  "bloom", "bluff", "blush", "booth", "brass", "brisk", "broom", "brush", "bunny",
  "burst", "chill", "cider", "clasp", "clove", "crisp", "curse", "dandy", "depot",
  "drape", "dusty", "ember", "enjoy", "fairy", "fancy", "frost", "fungi", "gleam",
  "grape", "grove", "hazel", "honey", "hound", "idyll", "inlet", "jolly", "kneel",
  "leafy", "lilac", "linen", "lofty", "lotus", "lunar", "mirth", "mossy", "mural",
  "nifty", "ninja", "nudge", "oasis", "otter", "petal", "plume", "plush", "prune",
  "quill", "quirk", "quota", "rainy", "relic", "rural", "saint", "silky", "sleek",
  "snail", "spear", "spine", "spool", "stalk", "stash", "stork", "swirl", "thief",
  "thorn", "tidal", "torch", "twine", "valet", "verge", "vista", "weird", "wharf",
  "wispy", "woody", "yacht", "yearn", "zesty", "zippy", "azure", "basil", "bring",
  "blame", "clean", "drink", "blink", "think", "drive", "sweep", "swing", "spend",
  "fling", "grind", "stand", "blend", "close", "clamp", "plant", "slack", "skate",
  "crack", "email", "shape", "trace", "watch", "crave", "plumb", "shine", "craft",
  "fluff", "punch", "stare", "waste", "slope", "chase", "split", "snare", "slink",
  "smoke", "steal", "climb", "stint", "reach"
];
